language: groovy
jdk:
- oraclejdk8
sudo: false
branches:
  only:
  - master
  - grails3
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: YIV236sD8Lr85/PChMktBgsu5gV8nXKgRp39tcHXxyzE6eXIeXI6jkI09yRSDPKaP0kxmsMHHu0YUVPr63dzFppiW+5t+lbXADw+SaZ00Q/7/HnDSF94yq2frMnb30P2bGBAf06WHlaExWlA/3XCagaCNPalD98qVpypPWjLr9SoWJ1UV/RanoSRYZ34NL/Vh/2V0AgM1/+As64r1c+5MOwMVMsG4M0grXjIDOzpBr6HIDlTYtCFMOybEV7dL0V7eklbpNBVxWlDrzkDF84pTnBftU7Vcy4egJ5x7wh23F9jRW3M/aS46yZ+ua9yRLHjhUYqN6p4iteTkVnSFI894uyq2ZyN07GV6QHC9Zmv2mVkEyxcVWJPOXRvL0au4PMWaWhlNrMVi2VlNk3+YX3CLTujnwdB5rppR8FIoZ1W9yxFdyy5bJmcgG/1Hv4cJI+VurOmrYpXwbcNlP3ky7m2hzkZdhDkFI8TXLO6lNFN2b2W3iXwGH7M3nyCUck8lQ2GWECOZc0+9t7+dmdrJFZPwKrCLEUqrWeX0tycwJvHN3IbgUx6MkIjkSEqXHjGjDEztvGXoMcdWGmMx32SAFTX++W+jg/oxCHHzk4yxSV/5R2LwBLMoWJcX7jHPE4QlcfWxpg7pzGwD1l2wJ5CHKztCG87prCGeuM+9KURUnHXn98=
  - secure: hZql6gTqd04Vu/M1MXXYQO+b0qOV1fKuPM7CDZ1aSE5XUEh0afa2fg5590e7TuF2wFDayRhusOL9wUaN13D+KiGlQ/rndq7+UUxfvLfQhMcB/igFE1idD/ogQXgmtjmo0zI0onbcPGqMxrDWp/8k5dAia7Ju2T/NKgFbJ0AYrFPMv+J9Bd21b7GACVtuu/mLpEEmPY4SoTpsRfxEnJNGVS/HsLZ5726nLSxa+D/YeMucUDhxMzcYReLqI5L/EmmEXQb7BqJJsL9mGxKJ+TK21HVZRmPK5W7NQ+A2f8bjr1ARX9q7H/vxc76W65pFXZaY+5howmci6YLYAbRcPIN6wqE2+t1G3KxMxIu+ry3WcbdzKNqG1CWMOdGrLHk/TXhXBidllAL1pcDFqoRDyB9vn3NtfSUa2n7QC8Nbc+bhLyo6rYz6R/medK+xxgEu3e/J2WfPi2TKeDFSvGSZSbwjCLUv/H/Yb6WAi48JhWX3HfSojvqpR1jeArI7CT8H0x0J3+/dcDsYgq2VHgVCp4S27lJyw7zT7P8SaQtNNPQOsRounkhp3Wu5yrRmHkqY97on2hQtjX+JK8h+DlJVI++t50pZSF1ffSTq/g5HD7HRQ5WUUTIyL5WbZ19hijrjY0nFl6vcBfXXih9Fzzm24sJJ6FtN/BHAiTcfOK4aAsaMmWw=
